version: '3.8'
services:
  minecraft:
    image: killruana/minecraft-server:main
    environment:
      EULA: "true"
      TYPE: "FORGE"
      MOD_PLATFORM: MODRINTH
      VERSION: "1.20.1"
      NEOFORGE_VERSION: "latest"
      MODRINTH_MODPACK: "/modpacks/kamoulox.mrpack"

    ports:
      - "25565:25565"
    volumes:
      - minecraft-data:/data
      - minecraft-mods:/modpacks

volumes:
  minecraft-data:
  minecraft-mods:


